- hosts: 192.168.43.215

  tasks:

  - name: "Copying JDK Software"
    copy: 
      dest: "/root"
      src: "/root/jdk-8u171-linux-x64.rpm"

  - name: "Copying Hadoop Software"
    copy:
      dest: "/root"
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"

  - name: "Installing JDK Software"
    command: "rpm -i jdk-8u171-linux-x64.rpm"

  - name: "Installing Hadoop Software"
    command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
     

      # NAME NODE SETUP 

- hosts: 192.168.43.128

  vars_prompt:
     - name: "NN_dir"
       private: no
       prompt: "Enter Name Node Directory "

  tasks:

  - name: "hdfs-site file in NameNode"
    template:
      dest: "/etc/hadoop/hdfs-site.xml"
      src: "/root/ansible-ws/hadoop/hd_nn.xml"

  - name: "core-site file in NameNode"
    template:
      dest: "/etc/hadoop/core-site.xml"
      src: "/root/ansible-ws/hadoop/cs.xml"

  - name: "Starting Name Node Services"
    command: "hadoop-daemon.sh start namenode"


      # DATA NODES SETUP
      
- hosts: 192.168.43.215

  vars_prompt:
     - name: "DN_dir"
       private: no
       prompt: "Enter Data Node Directory "
 
  tasks:
          
  - name: "hdfs-site file in Data Node"
    template:
      dest: "/etc/hadoop/hdfs-site.xml"
      src: "/root/ansible-ws/hadoop/hd_dn.xml"

  - name: "core-site file in Data Node"
    template:
      dest: "/etc/hadoop/core-site.xml"
      src: "/root/ansible-ws/hadoop/cs.xml"


  - name: "Starting Data Node Services"
    command: "hadoop-daemon.sh start datanode"
    
